name: CI - Explorador de Países

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master]

jobs:
  test-fastapi:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: Jer123456789
          MYSQL_DATABASE: countries_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: 📥 Clonar repositorio
      uses: actions/checkout@v3

    - name: 🐍 Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: 📦 Instalar dependencias
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: 🚀 Iniciar app y probar endpoint
      run: |
        uvicorn main:app --host 127.0.0.1 --port 8000 &
        sleep 10
        curl --fail http://127.0.0.1:8000/api/countries/all
